### ISSUE TITLE
weapons dosent show

### ISSUE THREAD

**Issue by kevinboeger** [MezoPlays/eBase#2]
Hey, i addet some weapons and vests on the crates. The stuff is in when i buy it but some stuff isnt in the list on the right side

InstaDoc:1
EMRE:1
Water:1
:1
:1
:1

its not showing the name like Katiba

**Comment by MezoPlays** [comment]
Nope, It won't work because I haven't added support for weapons. It only checks for Magazines&Items.

It's not something I'm willing to add either, as I don't think you should be able to buy weapons from eBase.
